Add hide_column_if Column attr_accessor
activescaffold/active_scaffold pull request #695
Opened 2022-11-22 21:12 UTC by moracca

Add a new attr_accessor to the DataStructures::Column module to allow for calling a dynamic Proc to determine whether a form column should be shown or not.

When hidden, render a dl element that can still be re-rendered by the update_columns routine so we will re-evaluate the proc whenever the column is re-rendered.

The value can be set a Proc in the scaffold controller as follows: config.columns[:my_column].hide_column_if = Proc.new { |record, column, scope| record.should_be_hidden? }

OR to always hide, use:
config.columns[:my_column].hide_column_if = true

This is useful when you want the column to be accessible via API but do not want it to be visible in the HTML form.

2022-11-23 08:06 UTC, scambra commented
I don't think we need this, you can override render_column in your helper like this:

```
def render_column(column, record, renders_as, scope = nil, *)
  if column == :my_column && record.should_be_hidden?
    # creates an element that can be replaced by the update_columns routine,
    # but will not affect the value of the submitted form in this state:
    # <dl><input type="hidden" class="<%= column.name %>-input"></dl>
    content_tag :dl, style: 'display: none' do
      hidden_field_tag(nil, nil, :class => "#{column.name}-input")
    end
  else
    super
  end
end
```

2022-11-23 08:31 UTC, moracca commented
That is certainly true that it can be done in the helper.  However we are conditionally hiding many columns across many different scaffolds, and for us it doesn't make much sense to keep redefining this method in every scaffold's helper with the specific set of criteria for that scaffold's columns, as it's a lot of code duplication.

But no worries, we can just continue monkey patching this functionality into our codebase.

2022-11-23 19:24 UTC, moracca commented
If I were to implement it as a helper override, I would want to override it on a per-scaffold basis.  Otherwise I would need to have a very long procedure of checking which scaffold we are currently referring to, then checking for any of the columns that should be hidden (which may not always correspond to a simple method call on the object).  The example I gave (calling `record.should_be_hidden?`) was a bit contrived, in reality the conditions may be more complex, and vary from column to column.  The same column may be conditionally hidden _differently_ in different scaffolds, so that means we need to check which controller/scaffold we are currently dealing with in addition to checking column's name.

Putting all of that logic for all of my scaffolds into a single place seems messy, and copying the render_column override into many scaffold helpers seems like an unnecessary amount of code duplication.  My personal preference is to be able to define this behavior in the scaffold config for the relevant scaffold controller and columns with a one-line config entry in the scaffold config.

2022-11-23 21:32 UTC, gregschmit commented
I recommended that Lannar upstream this because we find it very helpful to make dynamic forms that respond (appear/disappear) based on other form inputs. An example is checking a checkbox and having other related fields dynamically show up underneath that are only relevant if that checkbox is checked. We can of course keep this in our own project, however it seemed extremely useful and not really specific to our project so that's why I suggested upstreaming it.

2022-11-24 13:16 UTC, scambra commented
Ok, I will accept this PR with the changes I asked for in the review

2022-11-25 15:10 UTC, moracca commented
Maybe I am missing something simple but I can't find what changes you are referring to.

2022-11-26 00:16 UTC, scambra requested changes
Make changes in render_column

2022-11-26 00:17 UTC, scambra commented
I never used review before, I just added some comments but didn't send review, maybe you couldn't see them yet. I think you can see the review now

2022-11-26 11:37 UTC, moracca commented on lib/active_scaffold/helpers/form_column_helpers.rb
> +        if (column.hide_column_if.respond_to?(:call) ? column.hide_column_if.call(record, column, scope) : column.hide_column_if)
I implemented this change, and updated the attr_accessor name to hide_form_column_if to be more clear that this is referring only to form columns.  Let me know if that looks ok.

2022-11-28 11:51 UTC, merged

2022-11-28 11:56 UTC, scambra reviewed
Good

2022-11-28 14:08 UTC, moracca commented
Thanks!